# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:56:16+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Priority(Enum):
    NORMAL = 'NORMAL'
    HIGH = 'HIGH'


class AndroidFcmOptions(BaseModel):
    analyticsLabel: Optional[str] = Field(
        None, description="Label associated with the message's analytics data."
    )


class NotificationPriority(Enum):
    PRIORITY_UNSPECIFIED = 'PRIORITY_UNSPECIFIED'
    PRIORITY_MIN = 'PRIORITY_MIN'
    PRIORITY_LOW = 'PRIORITY_LOW'
    PRIORITY_DEFAULT = 'PRIORITY_DEFAULT'
    PRIORITY_HIGH = 'PRIORITY_HIGH'
    PRIORITY_MAX = 'PRIORITY_MAX'


class Visibility(Enum):
    VISIBILITY_UNSPECIFIED = 'VISIBILITY_UNSPECIFIED'
    PRIVATE = 'PRIVATE'
    PUBLIC = 'PUBLIC'
    SECRET = 'SECRET'


class ApnsFcmOptions(BaseModel):
    analyticsLabel: Optional[str] = Field(
        None, description="Label associated with the message's analytics data."
    )
    image: Optional[str] = Field(
        None,
        description='Contains the URL of an image that is going to be displayed in a notification. If present, it will override google.firebase.fcm.v1.Notification.image.',
    )


class Color(BaseModel):
    alpha: Optional[float] = Field(
        None,
        description='The fraction of this color that should be applied to the pixel. That is, the final pixel color is defined by the equation: `pixel color = alpha * (this color) + (1.0 - alpha) * (background color)` This means that a value of 1.0 corresponds to a solid color, whereas a value of 0.0 corresponds to a completely transparent color. This uses a wrapper message rather than a simple float scalar so that it is possible to distinguish between a default value and the value being unset. If omitted, this color object is rendered as a solid color (as if the alpha value had been explicitly given a value of 1.0).',
    )
    blue: Optional[float] = Field(
        None,
        description='The amount of blue in the color as a value in the interval [0, 1].',
    )
    green: Optional[float] = Field(
        None,
        description='The amount of green in the color as a value in the interval [0, 1].',
    )
    red: Optional[float] = Field(
        None,
        description='The amount of red in the color as a value in the interval [0, 1].',
    )


class FcmOptions(BaseModel):
    analyticsLabel: Optional[str] = Field(
        None, description="Label associated with the message's analytics data."
    )


class LightSettings(BaseModel):
    color: Optional[Color] = Field(
        None,
        description='Required. Set `color` of the LED with [google.type.Color](https://github.com/googleapis/googleapis/blob/master/google/type/color.proto).',
    )
    lightOffDuration: Optional[str] = Field(
        None,
        description='Required. Along with `light_on_duration `, define the blink rate of LED flashes. Resolution defined by [proto.Duration](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Duration)',
    )
    lightOnDuration: Optional[str] = Field(
        None,
        description='Required. Along with `light_off_duration`, define the blink rate of LED flashes. Resolution defined by [proto.Duration](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Duration)',
    )


class Notification(BaseModel):
    body: Optional[str] = Field(None, description="The notification's body text.")
    image: Optional[str] = Field(
        None,
        description='Contains the URL of an image that is going to be downloaded on the device and displayed in a notification. JPEG, PNG, BMP have full support across platforms. Animated GIF and video only work on iOS. WebP and HEIF have varying levels of support across platforms and platform versions. Android has 1MB image size limit. Quota usage and implications/costs for hosting image on Firebase Storage: https://firebase.google.com/pricing',
    )
    title: Optional[str] = Field(None, description="The notification's title.")


class WebpushFcmOptions(BaseModel):
    analyticsLabel: Optional[str] = Field(
        None, description="Label associated with the message's analytics data."
    )
    link: Optional[str] = Field(
        None,
        description='The link to open when the user clicks on the notification. For all URL values, HTTPS is required.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class AndroidNotification(BaseModel):
    body: Optional[str] = Field(
        None,
        description="The notification's body text. If present, it will override google.firebase.fcm.v1.Notification.body.",
    )
    bodyLocArgs: Optional[List[str]] = Field(
        None,
        description="Variable string values to be used in place of the format specifiers in body_loc_key to use to localize the body text to the user's current localization. See [Formatting and Styling](https://goo.gl/MalYE3) for more information.",
    )
    bodyLocKey: Optional[str] = Field(
        None,
        description="The key to the body string in the app's string resources to use to localize the body text to the user's current localization. See [String Resources](https://goo.gl/NdFZGI) for more information.",
    )
    bypassProxyNotification: Optional[bool] = Field(
        None,
        description='If set, display notifications delivered to the device will be handled by the app instead of the proxy.',
    )
    channelId: Optional[str] = Field(
        None,
        description="The [notification's channel id](https://developer.android.com/guide/topics/ui/notifiers/notifications#ManageChannels) (new in Android O). The app must create a channel with this channel ID before any notification with this channel ID is received. If you don't send this channel ID in the request, or if the channel ID provided has not yet been created by the app, FCM uses the channel ID specified in the app manifest.",
    )
    clickAction: Optional[str] = Field(
        None,
        description='The action associated with a user click on the notification. If specified, an activity with a matching intent filter is launched when a user clicks on the notification.',
    )
    color: Optional[str] = Field(
        None, description="The notification's icon color, expressed in #rrggbb format."
    )
    defaultLightSettings: Optional[bool] = Field(
        None,
        description="If set to true, use the Android framework's default LED light settings for the notification. Default values are specified in [config.xml](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/config.xml). If `default_light_settings` is set to true and `light_settings` is also set, the user-specified `light_settings` is used instead of the default value.",
    )
    defaultSound: Optional[bool] = Field(
        None,
        description="If set to true, use the Android framework's default sound for the notification. Default values are specified in [config.xml](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/config.xml).",
    )
    defaultVibrateTimings: Optional[bool] = Field(
        None,
        description="If set to true, use the Android framework's default vibrate pattern for the notification. Default values are specified in [config.xml](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/config.xml). If `default_vibrate_timings` is set to true and `vibrate_timings` is also set, the default value is used instead of the user-specified `vibrate_timings`.",
    )
    eventTime: Optional[str] = Field(
        None,
        description='Set the time that the event in the notification occurred. Notifications in the panel are sorted by this time. A point in time is represented using [protobuf.Timestamp](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Timestamp).',
    )
    icon: Optional[str] = Field(
        None,
        description="The notification's icon. Sets the notification icon to myicon for drawable resource myicon. If you don't send this key in the request, FCM displays the launcher icon specified in your app manifest.",
    )
    image: Optional[str] = Field(
        None,
        description='Contains the URL of an image that is going to be displayed in a notification. If present, it will override google.firebase.fcm.v1.Notification.image.',
    )
    lightSettings: Optional[LightSettings] = Field(
        None,
        description="Settings to control the notification's LED blinking rate and color if LED is available on the device. The total blinking time is controlled by the OS.",
    )
    localOnly: Optional[bool] = Field(
        None,
        description='Set whether or not this notification is relevant only to the current device. Some notifications can be bridged to other devices for remote display, such as a Wear OS watch. This hint can be set to recommend this notification not be bridged. See [Wear OS guides](https://developer.android.com/training/wearables/notifications/bridger#existing-method-of-preventing-bridging)',
    )
    notificationCount: Optional[int] = Field(
        None,
        description="Sets the number of items this notification represents. May be displayed as a badge count for launchers that support badging.See [Notification Badge](https://developer.android.com/training/notify-user/badges). For example, this might be useful if you're using just one notification to represent multiple new messages but you want the count here to represent the number of total new messages. If zero or unspecified, systems that support badging use the default, which is to increment a number displayed on the long-press menu each time a new notification arrives.",
    )
    notificationPriority: Optional[NotificationPriority] = Field(
        None,
        description="Set the relative priority for this notification. Priority is an indication of how much of the user's attention should be consumed by this notification. Low-priority notifications may be hidden from the user in certain situations, while the user might be interrupted for a higher-priority notification. The effect of setting the same priorities may differ slightly on different platforms. Note this priority differs from `AndroidMessagePriority`. This priority is processed by the client after the message has been delivered, whereas [AndroidMessagePriority](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidmessagepriority) is an FCM concept that controls when the message is delivered.",
    )
    sound: Optional[str] = Field(
        None,
        description='The sound to play when the device receives the notification. Supports "default" or the filename of a sound resource bundled in the app. Sound files must reside in /res/raw/.',
    )
    sticky: Optional[bool] = Field(
        None,
        description='When set to false or unset, the notification is automatically dismissed when the user clicks it in the panel. When set to true, the notification persists even when the user clicks it.',
    )
    tag: Optional[str] = Field(
        None,
        description='Identifier used to replace existing notifications in the notification drawer. If not specified, each request creates a new notification. If specified and a notification with the same tag is already being shown, the new notification replaces the existing one in the notification drawer.',
    )
    ticker: Optional[str] = Field(
        None,
        description='Sets the "ticker" text, which is sent to accessibility services. Prior to API level 21 (`Lollipop`), sets the text that is displayed in the status bar when the notification first arrives.',
    )
    title: Optional[str] = Field(
        None,
        description="The notification's title. If present, it will override google.firebase.fcm.v1.Notification.title.",
    )
    titleLocArgs: Optional[List[str]] = Field(
        None,
        description="Variable string values to be used in place of the format specifiers in title_loc_key to use to localize the title text to the user's current localization. See [Formatting and Styling](https://goo.gl/MalYE3) for more information.",
    )
    titleLocKey: Optional[str] = Field(
        None,
        description="The key to the title string in the app's string resources to use to localize the title text to the user's current localization. See [String Resources](https://goo.gl/NdFZGI) for more information.",
    )
    vibrateTimings: Optional[List[str]] = Field(
        None,
        description='Set the vibration pattern to use. Pass in an array of [protobuf.Duration](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Duration) to turn on or off the vibrator. The first value indicates the `Duration` to wait before turning the vibrator on. The next value indicates the `Duration` to keep the vibrator on. Subsequent values alternate between `Duration` to turn the vibrator off and to turn the vibrator on. If `vibrate_timings` is set and `default_vibrate_timings` is set to `true`, the default value is used instead of the user-specified `vibrate_timings`.',
    )
    visibility: Optional[Visibility] = Field(
        None,
        description='Set the [Notification.visibility](https://developer.android.com/reference/android/app/Notification.html#visibility) of the notification.',
    )


class ApnsConfig(BaseModel):
    fcmOptions: Optional[ApnsFcmOptions] = Field(
        None, description='Options for features provided by the FCM SDK for iOS.'
    )
    headers: Optional[Dict[str, str]] = Field(
        None,
        description='HTTP request headers defined in Apple Push Notification Service. Refer to [APNs request headers](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns) for supported headers such as `apns-expiration` and `apns-priority`. The backend sets a default value for `apns-expiration` of 30 days and a default value for `apns-priority` of 10 if not explicitly set.',
    )
    payload: Optional[Dict[str, Any]] = Field(
        None,
        description='APNs payload as a JSON object, including both `aps` dictionary and custom payload. See [Payload Key Reference](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification). If present, it overrides google.firebase.fcm.v1.Notification.title and google.firebase.fcm.v1.Notification.body.',
    )


class WebpushConfig(BaseModel):
    data: Optional[Dict[str, str]] = Field(
        None,
        description='Arbitrary key/value payload. If present, it will override google.firebase.fcm.v1.Message.data.',
    )
    fcmOptions: Optional[WebpushFcmOptions] = Field(
        None, description='Options for features provided by the FCM SDK for Web.'
    )
    headers: Optional[Dict[str, str]] = Field(
        None,
        description='HTTP headers defined in webpush protocol. Refer to [Webpush protocol](https://tools.ietf.org/html/rfc8030#section-5) for supported headers, e.g. "TTL": "15".',
    )
    notification: Optional[Dict[str, Any]] = Field(
        None,
        description='Web Notification options as a JSON object. Supports Notification instance properties as defined in [Web Notification API](https://developer.mozilla.org/en-US/docs/Web/API/Notification). If present, "title" and "body" fields override [google.firebase.fcm.v1.Notification.title] and [google.firebase.fcm.v1.Notification.body].',
    )


class AndroidConfig(BaseModel):
    collapseKey: Optional[str] = Field(
        None,
        description='An identifier of a group of messages that can be collapsed, so that only the last message gets sent when delivery can be resumed. A maximum of 4 different collapse keys is allowed at any given time.',
    )
    data: Optional[Dict[str, str]] = Field(
        None,
        description='Arbitrary key/value payload. If present, it will override google.firebase.fcm.v1.Message.data.',
    )
    directBootOk: Optional[bool] = Field(
        None,
        description='If set to true, messages will be allowed to be delivered to the app while the device is in direct boot mode. See [Support Direct Boot mode](https://developer.android.com/training/articles/direct-boot).',
    )
    fcmOptions: Optional[AndroidFcmOptions] = Field(
        None, description='Options for features provided by the FCM SDK for Android.'
    )
    notification: Optional[AndroidNotification] = Field(
        None, description='Notification to send to android devices.'
    )
    priority: Optional[Priority] = Field(
        None,
        description='Message priority. Can take "normal" and "high" values. For more information, see [Setting the priority of a message](https://goo.gl/GjONJv).',
    )
    restrictedPackageName: Optional[str] = Field(
        None,
        description='Package name of the application where the registration token must match in order to receive the message.',
    )
    ttl: Optional[str] = Field(
        None,
        description='How long (in seconds) the message should be kept in FCM storage if the device is offline. The maximum time to live supported is 4 weeks, and the default value is 4 weeks if not set. Set it to 0 if want to send the message immediately. In JSON format, the Duration type is encoded as a string rather than an object, where the string ends in the suffix "s" (indicating seconds) and is preceded by the number of seconds, with nanoseconds expressed as fractional seconds. For example, 3 seconds with 0 nanoseconds should be encoded in JSON format as "3s", while 3 seconds and 1 nanosecond should be expressed in JSON format as "3.000000001s". The ttl will be rounded down to the nearest second.',
    )


class Message(BaseModel):
    android: Optional[AndroidConfig] = Field(
        None,
        description='Input only. Android specific options for messages sent through [FCM connection server](https://goo.gl/4GLdUl).',
    )
    apns: Optional[ApnsConfig] = Field(
        None,
        description='Input only. [Apple Push Notification Service](https://goo.gl/MXRTPa) specific options.',
    )
    condition: Optional[str] = Field(
        None,
        description='Condition to send a message to, e.g. "\'foo\' in topics && \'bar\' in topics".',
    )
    data: Optional[Dict[str, str]] = Field(
        None,
        description='Input only. Arbitrary key/value payload, which must be UTF-8 encoded. The key should not be a reserved word ("from", "message_type", or any word starting with "google" or "gcm"). When sending payloads containing only data fields to iOS devices, only normal priority (`"apns-priority": "5"`) is allowed in [`ApnsConfig`](/docs/reference/fcm/rest/v1/projects.messages#apnsconfig).',
    )
    fcmOptions: Optional[FcmOptions] = Field(
        None,
        description='Input only. Template for FCM SDK feature options to use across all platforms.',
    )
    name: Optional[str] = Field(
        None,
        description='Output Only. The identifier of the message sent, in the format of `projects/*/messages/{message_id}`.',
    )
    notification: Optional[Notification] = Field(
        None,
        description='Input only. Basic notification template to use across all platforms.',
    )
    token: Optional[str] = Field(
        None, description='Registration token to send a message to.'
    )
    topic: Optional[str] = Field(
        None,
        description='Topic name to send a message to, e.g. "weather". Note: "/topics/" prefix should not be provided.',
    )
    webpush: Optional[WebpushConfig] = Field(
        None,
        description='Input only. [Webpush protocol](https://tools.ietf.org/html/rfc8030) options.',
    )


class SendMessageRequest(BaseModel):
    message: Optional[Message] = Field(None, description='Required. Message to send.')
    validateOnly: Optional[bool] = Field(
        None,
        description='Flag for testing the request without actually delivering the message.',
    )
